### ISSUE TITLE
Project activity

### ISSUE THREAD

**Issue by vxe** [BrunoBonacci/safely#10]
I'm very interested in using the library in project, just wanted to confirm if maintenance was active or if it would be better to fork.  Great work and thanks in advance!

**Comment by BrunoBonacci** [comment]
Hi Vijay,

The project is active, and used in several large projects.
It has reached stability so there hasn't been a lot of movement later.

I still marked as `alpha` because I changed the internal metric/tracking system from [samsara/TrackIt](https://github.com/samsara/trackit) to [µ/log](https://github.com/BrunoBonacci/mulog) and I wanted to give everybody the time to update and provide feedback, but the library has been stable for a while.

bye
Bruno
