### ISSUE TITLE
Use with asynchronous libraries

### ISSUE THREAD

**Issue by misterzirillo** [BrunoBonacci/safely#2]
Hello!

I'm trying to do something that I'm not sure is supported by this library. Consider the following code:

```clojure
(defn process-response [response] ...)
(safely
  ;; async callback
  (http/get url process-response)
  :on-error
  :max-retries 3)
```

In this situation safely does not capture an exception that happens in the callback function. How might I change this code to take advantage of safely?

**Comment by BrunoBonacci** [comment]
Hi @mrcirillo,

Happy New Year and sorry for the delay in the response.

The short answer is: **no, you can't**. Currently `safely` doesn't support async operations.

The reason is that in an asynchronous system you essentially need two facilities: a way to chain computation asynchronously and a platform to execute these chains.
Unfortunately, these facilities were introduced very late in Java and Clojure so there is no standard way to do it. There are many libraries in both ecosystems which offer asynchronous processing but none of them can be considered the standard. So if you pick one library or one approach it is likely that it will only work for a subset of the projects.

For example:
  - Java 8 added the `CompletableFuture` (https://www.baeldung.com/java-completablefuture)
  - Cloujure has `core.async`
  - There is the excellent library from @ztellman [Manifold](https://github.com/ztellman/manifold)
  - Most of the industry projects (I worked on) which focus on Async use Netty async facilities (event loop and pipelines)

`Safely` was designed for the synchronous case. It is mainly used for request/response type of requests like for databases, REST services and AWS APIs.
Most of the commonly used AWS libraries are synchronous, therefore, so far I didn't feel much the need for it.

The new [AWS SDK 2.x](https://aws.amazon.com/blogs/developer/aws-sdk-for-java-2-x-released/) supports async calls, but unfortunately it is not widely used yet.

In the longer term, I'd like to add the async support but I have no immediate plans/need for it.
I've been thinking a lot about which approach to take, but I haven't yet made a concrete decision yet.
Currently, my focus is going towards adding better support for observability around `Safely`,
so that out of the box you can have distributed tracing of `safely` wrapped calls.

`Safely` already provides metering information out-of-the-box (see [tracking](https://github.com/BrunoBonacci/safely/blob/master/doc/tracking.md) page),
but I'd like to have more contextual details; therefore I'm replacing the metrics with events (see [μ/log + μ/trace](https://github.com/BrunoBonacci/mulog) for more info)

I'm sorry I couldn't be more helpful this time, I hope you find a good alternative. If so, I'd like to know the approach used and the challenges faced so that I can make a more informed decision when I'll extend this library.

**Comment by misterzirillo** [comment]
Thanks for the response, @BrunoBonacci. This library is really helpful regardless.
